### ISSUE TITLE
Unexpected token < in JSON at position 0 on each route

### ISSUE THREAD

**Issue by isaacfink** [svelteness/kit-docs#3]
I copied the docs route folder from this repo as a starting point but I keep getting this error,
the only thing I changed in the folder is I removed the images (logo, and social card) and all the references to it, I also renamed layout to layout.reset because I have a root layout

I have a `[dir].sidebar.json.js` with the following code
```
import { createSidebarRequestHandler } from '@svelteness/kit-docs/node';

export const get = createSidebarRequestHandler();
```

and `[slug].meta.json.js`
```
import { createMetaRequestHandler } from '@svelteness/kit-docs/node';

export const get = createMetaRequestHandler();
```

this is my svelte config
```
import preprocess from 'svelte-preprocess';
import adapter from '@sveltejs/adapter-auto';
import {kitDocsPlugin} from '@svelteness/kit-docs/node'
import Icons from 'unplugin-icons/vite'

/** @type {import('@sveltejs/kit').Config} */
const config = {
	extensions: ['.svelte', '.md'],
	kit: {
		adapter: adapter(),
		vite:{
			optimizeDeps: {
				exclude: ['@urql/svelte', '@urql/core'],
			  },

			  plugins: [
				  Icons({compiler: 'svelte'}),
				  kitDocsPlugin({
					  shiki: {
						  theme: 'material-ocean'
					  },
				  }),
			  ],
			
		}
	},

	preprocess: [
		preprocess({
			postcss: true
		})
	]
};

export default config;

```

I always get the same error, 
```
500
Unexpected token < in JSON at position 0
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Proxy.<anonymous> (file:///Users/isaac/Desktop/projects/saffron/redo/frontend/.svelte-kit/runtime/server/index.js:1797:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async eval (/node_modules/@svelteness/kit-docs/client/loaders/index.js:22:22)
    at async load_node (file:///Users/isaac/Desktop/projects/saffron/redo/frontend/.svelte-kit/runtime/server/index.js:1826:12)
    at async respond$1 (file:///Users/isaac/Desktop/projects/saffron/redo/frontend/.svelte-kit/runtime/server/index.js:2177:15)
    at async render_page (file:///Users/isaac/Desktop/projects/saffron/redo/frontend/.svelte-kit/runtime/server/index.js:2378:19)
    at async resolve (file:///Users/isaac/Desktop/projects/saffron/redo/frontend/.svelte-kit/runtime/server/index.js:2610:11)
    at async respond (file:///Users/isaac/Desktop/projects/saffron/redo/frontend/.svelte-kit/runtime/server/index.js:2543:20)
    at async file:///Users/isaac/Desktop/projects/saffron/redo/frontend/node_modules/@sveltejs/kit/dist/chunks/index.js:244:24
```

**Comment by isaacfink** [comment]
I am not using typescript so I didn't include an of the types

**Comment by didier** [comment]
I noticed that root routes don't work, e.g.: you can't use kit-docs at `/`, but you can at `/docs/` or something that's at least one level deep.

**Comment by mihar-22** [comment]
Probably the loader is failing to normalize the slug. Can you push your code up to a repo that you can share with me. It'd help me debug way faster.

**Comment by Myrmod** [comment]
I got the same kind of error if I am not mistaken:

https://github.com/Myrmod/svelte-babylon/tree/kit-docs

```sh
git clone git@github.com:Myrmod/svelte-babylon.git && cd svelte-babylon
git checkout kit-docs
npm ci
npm run dev
```

**Comment by mihar-22** [comment]
This should be resolved in the latest. Added better loader fail handling and the default layout has better meta `null` checks too.

**Comment by isaacfink** [comment]
I tried on multiple routes so it's not only the root route, what's the latest?

**Comment by mihar-22** [comment]
upgrade to `0.6.1` -> `npm i @svelteness/kit-docs@^0.6.1 -D`

**Comment by isaacfink** [comment]
So i upgraded and it's still not working, here is a repo with a reproduction, please let me know when I can delete the repo
[git@github.com:isaacfink/svelteness-kit-docs-issue.git](https://github.com/isaacfink/svelteness-kit-docs-issue.git)

**Comment by mihar-22** [comment]
Thanks heaps for the repro @isaacfink. The issue seemed to be that `shiki` wasn't being optimized by Vite and failing server-side import. I've included by default now. You can delete the repo right after you test if `0.7.2` fixes things on your end.

**Comment by isaacfink** [comment]
Thanks such I'll test it tomorrow and let you know, if you don't mind explaining in short what is shiki? I saw it's in the config but I had no idea what it does, is it the theme?

**Comment by mihar-22** [comment]
Syntax highlighter: https://shiki.matsu.io/

**Comment by isaacfink** [comment]
Also should I expect problems with deployment? Specifically with vercel?

**Comment by mihar-22** [comment]
I've personally deployed to Vercel without any issues. Feel free to test it out in a PR so it's not on your main site. If you run into any issues let me know in a new issue.

**Comment by Myrmod** [comment]
Since 0.7.2 it works fine. Thank you a lot :)

**Comment by isaacfink** [comment]
It works now but I have a different issue now, the sidebar disappears after a second

**Comment by mihar-22** [comment]
Thanks @isaacfink. I'm looking in to it now.
